import { defineConfig } from "@hey-api/openapi-ts";

// Generated by `mise run generate:openapi` (or `ensure:openapi` on first dev/build).
const input = "./openapi.json";

export default defineConfig({
  input,
  output: "./src/client",
  plugins: [
    {
      name: "@hey-api/client-fetch",
      throwOnError: true,
    },
  ],
});
