repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
        args: [--unsafe]
      - id: end-of-file-fixer
        exclude: ^frontend/src/client/
      - id: trailing-whitespace
        exclude: ^frontend/src/client/

  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: uv run ruff check --force-exclude --fix --exit-non-zero-on-fix
        require_serial: true
        language: system
        types: [python]

      - id: ruff-format
        name: ruff format
        entry: uv run ruff format --force-exclude --exit-non-zero-on-format
        require_serial: true
        language: system
        types: [python]

      - id: ty
        name: ty check
        entry: uv run --directory backend ty check
        require_serial: true
        language: system
        pass_filenames: false

      - id: eslint
        name: eslint
        entry: mise run lint:frontend
        language: system
        files: ^frontend/.*\.(ts|tsx|vue|js|jsx)$
        pass_filenames: false

      - id: vulture
        name: vulture
        entry: mise run deadcode:backend
        require_serial: true
        language: system
        types: [python]
        pass_filenames: false

      - id: knip
        name: knip
        entry: mise run deadcode:frontend
        require_serial: true
        language: system
        files: ^frontend/.*\.(ts|tsx|vue|js|jsx)$
        pass_filenames: false
