services:

  db:
    restart: "no"
    ports:
      - "5432:5432"

  backend:
    restart: "no"
    ports:
      - "8000:8000"
    command:
      - uvicorn
      - app.main:app
      - --reload
      - --host
      - "0.0.0.0"
      - --no-access-log
    develop:
      watch:
        - path: ./backend
          action: sync
          target: /app/backend
          ignore:
            - ./backend/.venv
            - .venv
        - path: ./backend/pyproject.toml
          action: rebuild

  frontend:
    restart: "no"
    ports:
      - "5173:80"
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - VITE_BACKEND_URL=http://localhost:8000
        - NODE_ENV=development
