services:

  db:
    restart: "no"
    ports:
      - "127.0.0.1:5432:5432"

  app:
    image: wanderbound:dev
    pull_policy: build
    restart: "no"
    ports:
      - "127.0.0.1:8000:8000"
    command: sh -c "alembic upgrade head && uvicorn app.main:app --reload --host 0.0.0.0 --proxy-headers --log-config app/core/uvicorn_logging.json"
    build:
      context: .
      dockerfile: Dockerfile
      target: app
      args:
        APP_VERSION: dev
    develop:
      watch:
        - path: ./backend
          action: sync
          target: /app/backend
          ignore:
            - ./backend/.venv
            - .venv
        - path: ./backend/pyproject.toml
          action: rebuild
        - path: ./frontend
          action: rebuild

  sourcemaps:
    image: wanderbound-sourcemaps:dev
    pull_policy: build
    build:
      context: .
      dockerfile: Dockerfile
      target: sourcemaps
      args:
        APP_VERSION: dev

networks:
  backend:
    internal: false
  frontend:
    external: false
