services:

  db:
    image: postgres:18
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}

  prestart:
    image: 'backend:${TAG:-latest}'
    build:
      context: .
      dockerfile: backend/Dockerfile
    depends_on:
      db:
        condition: service_healthy
        restart: true
    command: bash scripts/prestart.sh
    env_file:
      - .env
    environment:
      - POSTGRES_SERVER=db
    volumes:
      - app-data:/app/backend/data

  backend:
    image: 'backend:${TAG:-latest}'
    restart: always
    depends_on:
      db:
        condition: service_healthy
        restart: true
      prestart:
        condition: service_completed_successfully
    env_file:
      - .env
    environment:
      - POSTGRES_SERVER=db
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/api/v1/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - app-data:/app/backend/data

  frontend:
    image: 'frontend:${TAG:-latest}'
    restart: always
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - VITE_BACKEND_URL=https://api.${DOMAIN?Variable not set}
        - VITE_MAPBOX_TOKEN=${VITE_MAPBOX_TOKEN}

volumes:
  db-data:
  app-data:
