services:

  db:
    restart: "no"
    ports:
      - "5432:5432"

  prestart:
    volumes:
      - ./backend:/app/backend

  backend:
    restart: "no"
    ports:
      - "8000:8000"
    command:
      - uvicorn
      - app.main:app
      - --reload
      - --host
      - "0.0.0.0"
      - --proxy-headers
      - --log-config
      - logging.json
    develop:
      watch:
        - path: ./backend
          action: sync
          target: /app/backend
          ignore:
            - ./backend/.venv
            - .venv
        - path: ./backend/pyproject.toml
          action: rebuild

  frontend:
    restart: "no"
    ports:
      - "5173:8080"
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - VITE_BACKEND_URL=http://localhost:8000
