from typing import Self

class options:
    default_adapter_factory = ...
    default_proxies = ...
    default_scheme = ...
    default_ssl_context = ...
    default_timeout = ...
    default_user_agent = ...

class Geocoder:
    def __init__(
        self,
        *,
        scheme=...,
        timeout=...,
        proxies=...,
        user_agent=...,
        ssl_context=...,
        adapter_factory=...,
    ) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type, exc_val, exc_tb) -> None: ...
    async def __aenter__(self) -> Self: ...
    async def __aexit__(self, exc_type, exc_val, exc_tb) -> None: ...
