// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { AdjustSegmentBoundaryData, AdjustSegmentBoundaryErrors, AdjustSegmentBoundaryResponses, AuthenticateData, AuthenticateErrors, AuthenticateResponses, DeleteUserData, DeleteUserResponses, DownloadExportData, DownloadExportErrors, DownloadExportResponses, DownloadPdfData, DownloadPdfErrors, DownloadPdfResponses, ExportDataData, ExportDataResponses, GeneratePdfData, GeneratePdfErrors, GeneratePdfResponses, GetMediaData, GetMediaErrors, GetMediaResponses, HealthCheckData, HealthCheckResponses, LogoutData, LogoutResponses, ProcessUserData, ProcessUserResponses, ReadAlbumData, ReadAlbumErrors, ReadAlbumResponses, ReadMediaData, ReadMediaErrors, ReadMediaResponses, ReadPrintBundleData, ReadPrintBundleErrors, ReadPrintBundleResponses, ReadSegmentPointsData, ReadSegmentPointsErrors, ReadSegmentPointsResponses, ReadSegmentsData, ReadSegmentsErrors, ReadSegmentsResponses, ReadStepsData, ReadStepsErrors, ReadStepsResponses, ReadUserData, ReadUserResponses, UpdateAlbumData, UpdateAlbumErrors, UpdateAlbumResponses, UpdateStepData, UpdateStepErrors, UpdateStepResponses, UpdateUserData, UpdateUserErrors, UpdateUserResponses, UpdateVideoFrameData, UpdateVideoFrameErrors, UpdateVideoFrameResponses, UploadDataData, UploadDataErrors, UploadDataResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health Check
 */
export const healthCheck = <ThrowOnError extends boolean = true>(options?: Options<HealthCheckData, ThrowOnError>) => (options?.client ?? client).get<HealthCheckResponses, unknown, ThrowOnError>({ url: '/api/v1/health', ...options });

/**
 * Logout
 */
export const logout = <ThrowOnError extends boolean = true>(options?: Options<LogoutData, ThrowOnError>) => (options?.client ?? client).post<LogoutResponses, unknown, ThrowOnError>({ url: '/api/v1/auth/logout', ...options });

/**
 * Authenticate
 */
export const authenticate = <ThrowOnError extends boolean = true>(options: Options<AuthenticateData, ThrowOnError>) => (options.client ?? client).post<AuthenticateResponses, AuthenticateErrors, ThrowOnError>({
    url: '/api/v1/auth/{provider}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Upload Data
 */
export const uploadData = <ThrowOnError extends boolean = true>(options: Options<UploadDataData, ThrowOnError>) => (options.client ?? client).post<UploadDataResponses, UploadDataErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/api/v1/users/upload',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Process User
 */
export const processUser = <ThrowOnError extends boolean = true>(options?: Options<ProcessUserData, ThrowOnError>) => (options?.client ?? client).sse.get<ProcessUserResponses, unknown, ThrowOnError>({ url: '/api/v1/users/process', ...options });

/**
 * Export Data
 */
export const exportData = <ThrowOnError extends boolean = true>(options?: Options<ExportDataData, ThrowOnError>) => (options?.client ?? client).sse.get<ExportDataResponses, unknown, ThrowOnError>({ url: '/api/v1/users/export', ...options });

/**
 * Download Export
 */
export const downloadExport = <ThrowOnError extends boolean = true>(options: Options<DownloadExportData, ThrowOnError>) => (options.client ?? client).get<DownloadExportResponses, DownloadExportErrors, ThrowOnError>({ url: '/api/v1/users/export/download/{token}', ...options });

/**
 * Delete User
 */
export const deleteUser = <ThrowOnError extends boolean = true>(options?: Options<DeleteUserData, ThrowOnError>) => (options?.client ?? client).delete<DeleteUserResponses, unknown, ThrowOnError>({ url: '/api/v1/users', ...options });

/**
 * Read User
 */
export const readUser = <ThrowOnError extends boolean = true>(options?: Options<ReadUserData, ThrowOnError>) => (options?.client ?? client).get<ReadUserResponses, unknown, ThrowOnError>({ url: '/api/v1/users', ...options });

/**
 * Update User
 */
export const updateUser = <ThrowOnError extends boolean = true>(options: Options<UpdateUserData, ThrowOnError>) => (options.client ?? client).patch<UpdateUserResponses, UpdateUserErrors, ThrowOnError>({
    url: '/api/v1/users',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Download Pdf
 */
export const downloadPdf = <ThrowOnError extends boolean = true>(options: Options<DownloadPdfData, ThrowOnError>) => (options.client ?? client).get<DownloadPdfResponses, DownloadPdfErrors, ThrowOnError>({ url: '/api/v1/albums/pdf/download/{token}', ...options });

/**
 * Read Album
 */
export const readAlbum = <ThrowOnError extends boolean = true>(options: Options<ReadAlbumData, ThrowOnError>) => (options.client ?? client).get<ReadAlbumResponses, ReadAlbumErrors, ThrowOnError>({ url: '/api/v1/albums/{aid}', ...options });

/**
 * Update Album
 */
export const updateAlbum = <ThrowOnError extends boolean = true>(options: Options<UpdateAlbumData, ThrowOnError>) => (options.client ?? client).patch<UpdateAlbumResponses, UpdateAlbumErrors, ThrowOnError>({
    url: '/api/v1/albums/{aid}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Read Media
 */
export const readMedia = <ThrowOnError extends boolean = true>(options: Options<ReadMediaData, ThrowOnError>) => (options.client ?? client).get<ReadMediaResponses, ReadMediaErrors, ThrowOnError>({ url: '/api/v1/albums/{aid}/media', ...options });

/**
 * Read Steps
 */
export const readSteps = <ThrowOnError extends boolean = true>(options: Options<ReadStepsData, ThrowOnError>) => (options.client ?? client).get<ReadStepsResponses, ReadStepsErrors, ThrowOnError>({ url: '/api/v1/albums/{aid}/steps', ...options });

/**
 * Read Segments
 */
export const readSegments = <ThrowOnError extends boolean = true>(options: Options<ReadSegmentsData, ThrowOnError>) => (options.client ?? client).get<ReadSegmentsResponses, ReadSegmentsErrors, ThrowOnError>({ url: '/api/v1/albums/{aid}/segments', ...options });

/**
 * Read Segment Points
 */
export const readSegmentPoints = <ThrowOnError extends boolean = true>(options: Options<ReadSegmentPointsData, ThrowOnError>) => (options.client ?? client).get<ReadSegmentPointsResponses, ReadSegmentPointsErrors, ThrowOnError>({ url: '/api/v1/albums/{aid}/segments/points', ...options });

/**
 * Update Step
 */
export const updateStep = <ThrowOnError extends boolean = true>(options: Options<UpdateStepData, ThrowOnError>) => (options.client ?? client).patch<UpdateStepResponses, UpdateStepErrors, ThrowOnError>({
    url: '/api/v1/albums/{aid}/steps/{sid}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Adjust Segment Boundary
 */
export const adjustSegmentBoundary = <ThrowOnError extends boolean = true>(options: Options<AdjustSegmentBoundaryData, ThrowOnError>) => (options.client ?? client).patch<AdjustSegmentBoundaryResponses, AdjustSegmentBoundaryErrors, ThrowOnError>({
    url: '/api/v1/albums/{aid}/segments/adjust-boundary',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Read Print Bundle
 */
export const readPrintBundle = <ThrowOnError extends boolean = true>(options: Options<ReadPrintBundleData, ThrowOnError>) => (options.client ?? client).get<ReadPrintBundleResponses, ReadPrintBundleErrors, ThrowOnError>({ url: '/api/v1/albums/{aid}/print-bundle', ...options });

/**
 * Generate Pdf
 */
export const generatePdf = <ThrowOnError extends boolean = true>(options: Options<GeneratePdfData, ThrowOnError>) => (options.client ?? client).sse.post<GeneratePdfResponses, GeneratePdfErrors, ThrowOnError>({ url: '/api/v1/albums/{aid}/pdf/generate', ...options });

/**
 * Get Media
 */
export const getMedia = <ThrowOnError extends boolean = true>(options: Options<GetMediaData, ThrowOnError>) => (options.client ?? client).get<GetMediaResponses, GetMediaErrors, ThrowOnError>({ url: '/api/v1/albums/{aid}/media/{name}', ...options });

/**
 * Update Video Frame
 */
export const updateVideoFrame = <ThrowOnError extends boolean = true>(options: Options<UpdateVideoFrameData, ThrowOnError>) => (options.client ?? client).patch<UpdateVideoFrameResponses, UpdateVideoFrameErrors, ThrowOnError>({ url: '/api/v1/albums/{aid}/media/{name}', ...options });
