// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Album
 *
 * Full DB row. Only adds media - no relationships.
 */
export type Album = {
    /**
     * Title
     */
    title: string;
    /**
     * Subtitle
     */
    subtitle: string;
    /**
     * Hidden Steps
     */
    hidden_steps?: Array<number>;
    /**
     * Hidden Headers
     */
    hidden_headers?: Array<'cover-front' | 'cover-back' | 'overview' | 'full-map'>;
    /**
     * Maps Ranges
     */
    maps_ranges?: Array<DateRange>;
    /**
     * Front Cover Photo
     */
    front_cover_photo: string;
    /**
     * Back Cover Photo
     */
    back_cover_photo: string;
    /**
     * Font
     */
    font?: string;
    /**
     * Body Font
     */
    body_font?: string;
    /**
     * Safe Margin Mm
     */
    safe_margin_mm?: number;
    /**
     * Uid
     */
    uid: number;
    /**
     * Id
     */
    id: string;
    /**
     * Colors
     */
    colors: {
        [key: string]: unknown | string;
    };
    /**
     * Media
     */
    media?: Array<Media>;
    /**
     * Upgraded Media
     */
    upgraded_media?: {
        [key in MediaFilename]?: GoogleMediaId;
    };
};

/**
 * AlbumMeta
 *
 * GET/PATCH response - everything except media.
 */
export type AlbumMeta = {
    /**
     * Title
     */
    title: string;
    /**
     * Subtitle
     */
    subtitle: string;
    /**
     * Hidden Steps
     */
    hidden_steps?: Array<number>;
    /**
     * Hidden Headers
     */
    hidden_headers?: Array<'cover-front' | 'cover-back' | 'overview' | 'full-map'>;
    /**
     * Maps Ranges
     */
    maps_ranges?: Array<DateRange>;
    /**
     * Front Cover Photo
     */
    front_cover_photo: string;
    /**
     * Back Cover Photo
     */
    back_cover_photo: string;
    /**
     * Font
     */
    font?: string;
    /**
     * Body Font
     */
    body_font?: string;
    /**
     * Safe Margin Mm
     */
    safe_margin_mm?: number;
    /**
     * Uid
     */
    uid: number;
    /**
     * Id
     */
    id: string;
    /**
     * Colors
     */
    colors: {
        [key: string]: unknown | string;
    };
};

/**
 * AlbumUpdate
 */
export type AlbumUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Subtitle
     */
    subtitle?: string | null;
    /**
     * Hidden Steps
     */
    hidden_steps?: Array<number> | null;
    /**
     * Hidden Headers
     */
    hidden_headers?: Array<'cover-front' | 'cover-back' | 'overview' | 'full-map'> | null;
    /**
     * Maps Ranges
     */
    maps_ranges?: Array<DateRange> | null;
    /**
     * Front Cover Photo
     */
    front_cover_photo?: string | null;
    /**
     * Back Cover Photo
     */
    back_cover_photo?: string | null;
    /**
     * Font
     */
    font?: string | null;
    /**
     * Body Font
     */
    body_font?: string | null;
    /**
     * Safe Margin Mm
     */
    safe_margin_mm?: number | null;
};

/**
 * Body_upload_data
 */
export type BodyUploadData = {
    /**
     * File
     */
    file: Blob | File;
    /**
     * Credential
     */
    credential?: string | null;
    /**
     * Provider
     */
    provider?: 'google' | 'microsoft' | null;
};

/**
 * BoundaryAdjust
 */
export type BoundaryAdjust = {
    /**
     * Start Time
     */
    start_time: number;
    /**
     * End Time
     */
    end_time: number;
    /**
     * Handle
     */
    handle: 'start' | 'end';
    /**
     * New Boundary Time
     */
    new_boundary_time: number;
};

/**
 * Credential
 */
export type Credential = {
    /**
     * Credential
     */
    credential: string;
};

export type DateRange = [
    string,
    string
];

/**
 * ErrorData
 */
export type ErrorData = {
    /**
     * Type
     */
    type?: 'error';
};

/**
 * ExportDone
 */
export type ExportDone = {
    /**
     * Type
     */
    type?: 'done';
    /**
     * Token
     */
    token: string;
};

/**
 * ExportError
 */
export type ExportError = {
    /**
     * Type
     */
    type?: 'error';
    /**
     * Detail
     */
    detail?: string | null;
};

/**
 * ExportProgress
 */
export type ExportProgress = {
    /**
     * Type
     */
    type?: 'progress';
    /**
     * Files Done
     */
    files_done: number;
    /**
     * Files Total
     */
    files_total: number;
};

export type GoogleMediaId = string;

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthStatus
 */
export type HealthStatus = {
    /**
     * Db
     */
    db: boolean;
    /**
     * Disk
     */
    disk: boolean;
    /**
     * Playwright
     */
    playwright: boolean;
};

/**
 * Location
 */
export type Location = {
    /**
     * Name
     */
    name: string;
    /**
     * Detail
     */
    detail: string;
    /**
     * Country Code
     */
    country_code: string;
    /**
     * Lat
     */
    lat: number;
    /**
     * Lon
     */
    lon: number;
};

/**
 * MatchResult
 */
export type MatchResult = {
    local_name: MediaFilename;
    google_id: GoogleMediaId;
    /**
     * Distance
     */
    distance: number;
};

/**
 * Media
 */
export type Media = {
    /**
     * Name
     */
    name: string;
    /**
     * Width
     */
    width: number;
    /**
     * Height
     */
    height: number;
};

export type MediaFilename = string;

/**
 * PdfDone
 */
export type PdfDone = {
    /**
     * Type
     */
    type?: 'done';
    /**
     * Token
     */
    token: string;
};

/**
 * PdfError
 */
export type PdfError = {
    /**
     * Type
     */
    type?: 'error';
    /**
     * Detail
     */
    detail: string;
};

/**
 * PdfProgress
 */
export type PdfProgress = {
    /**
     * Type
     */
    type?: 'progress';
    /**
     * Phase
     */
    phase: 'loading' | 'rendering';
    /**
     * Done
     */
    done: number;
    /**
     * Total
     */
    total?: number | null;
};

/**
 * PdfQueued
 */
export type PdfQueued = {
    /**
     * Type
     */
    type?: 'queued';
};

/**
 * PhaseUpdate
 */
export type PhaseUpdate = {
    /**
     * Type
     */
    type?: 'phase';
    phase: ProcessingPhase;
    /**
     * Done
     */
    done: number;
    /**
     * Total
     */
    total: number;
};

export type PickerSessionId = string;

/**
 * PickerSessionResponse
 */
export type PickerSessionResponse = {
    session_id: PickerSessionId;
    /**
     * Picker Uri
     */
    picker_uri: string;
};

/**
 * Point
 */
export type Point = {
    /**
     * Lat
     */
    lat: number;
    /**
     * Lon
     */
    lon: number;
    /**
     * Time
     */
    time: number;
};

/**
 * PrintBundle
 *
 * Everything needed for PDF rendering in one response.
 */
export type PrintBundle = {
    album: Album;
    /**
     * Steps
     */
    steps: Array<Step>;
    /**
     * Segments
     */
    segments: Array<Segment>;
    /**
     * Total Distance Km
     */
    total_distance_km: number;
};

export type ProcessingPhase = 'elevations' | 'weather' | 'layouts';

/**
 * Segment
 */
export type Segment = {
    /**
     * Uid
     */
    uid: number;
    /**
     * Aid
     */
    aid: string;
    /**
     * Start Time
     */
    start_time: number;
    /**
     * End Time
     */
    end_time: number;
    kind: SegmentKind;
    /**
     * Timezone Id
     */
    timezone_id: string;
    /**
     * Points
     */
    points: Array<Point>;
    /**
     * Route
     */
    route?: Array<[
        number,
        number
    ]> | null;
};

/**
 * SegmentKind
 */
export type SegmentKind = 'flight' | 'hike' | 'walking' | 'driving';

/**
 * SegmentOutline
 *
 * Lightweight segment projection - no points or route.
 */
export type SegmentOutline = {
    /**
     * Start Time
     */
    start_time: number;
    /**
     * End Time
     */
    end_time: number;
    kind: SegmentKind;
    /**
     * Timezone Id
     */
    timezone_id: string;
    /**
     * Start Coord
     */
    start_coord: [
        number,
        number
    ];
    /**
     * End Coord
     */
    end_coord: [
        number,
        number
    ];
};

/**
 * SessionStatusResponse
 */
export type SessionStatusResponse = {
    /**
     * Ready
     */
    ready: boolean;
};

/**
 * Step
 */
export type Step = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
    /**
     * Cover
     */
    cover?: string | null;
    /**
     * Pages
     */
    pages: Array<Array<string>>;
    /**
     * Unused
     */
    unused: Array<string>;
    /**
     * Uid
     */
    uid: number;
    /**
     * Aid
     */
    aid: string;
    /**
     * Id
     */
    id: number;
    /**
     * Timestamp
     */
    timestamp: number;
    /**
     * Timezone Id
     */
    timezone_id: string;
    location: Location;
    /**
     * Elevation
     */
    elevation: number;
    weather: Weather;
    /**
     * Datetime
     */
    readonly datetime: string;
};

/**
 * StepUpdate
 */
export type StepUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Cover
     */
    cover?: string | null;
    /**
     * Pages
     */
    pages?: Array<Array<string>> | null;
    /**
     * Unused
     */
    unused?: Array<string> | null;
};

/**
 * TripMeta
 */
export type TripMeta = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Step Count
     */
    step_count: number;
    /**
     * Country Codes
     */
    country_codes: Array<string>;
};

/**
 * TripStart
 */
export type TripStart = {
    /**
     * Type
     */
    type?: 'trip_start';
    /**
     * Trip Index
     */
    trip_index: number;
};

/**
 * UpgradeDone
 */
export type UpgradeDone = {
    /**
     * Type
     */
    type?: 'done';
    /**
     * Replaced
     */
    replaced: number;
    /**
     * Failed
     */
    failed: number;
};

/**
 * UpgradeDownloading
 */
export type UpgradeDownloading = {
    /**
     * Type
     */
    type?: 'downloading';
    /**
     * Done
     */
    done: number;
    /**
     * Total
     */
    total: number;
};

/**
 * UpgradeError
 */
export type UpgradeError = {
    /**
     * Type
     */
    type?: 'error';
    /**
     * Detail
     */
    detail: string;
};

/**
 * UpgradeMatchSummary
 */
export type UpgradeMatchSummary = {
    /**
     * Type
     */
    type?: 'match_summary';
    /**
     * Total Media
     */
    total_media: number;
    /**
     * Matched
     */
    matched: number;
    /**
     * Unmatched
     */
    unmatched: number;
    /**
     * Matches
     */
    matches: Array<MatchResult>;
};

/**
 * UpgradeMatching
 */
export type UpgradeMatching = {
    /**
     * Type
     */
    type?: 'matching';
    /**
     * Phase
     */
    phase: string;
    /**
     * Done
     */
    done: number;
    /**
     * Total
     */
    total: number;
};

/**
 * UpgradeReplacing
 */
export type UpgradeReplacing = {
    /**
     * Type
     */
    type?: 'replacing';
    /**
     * Done
     */
    done: number;
    /**
     * Total
     */
    total: number;
};

/**
 * UpgradeRequest
 */
export type UpgradeRequest = {
    session_id: PickerSessionId;
    /**
     * Matches
     */
    matches: Array<MatchResult>;
};

/**
 * UploadResult
 */
export type UploadResult = {
    user: User;
    /**
     * Trips
     */
    trips: Array<TripMeta>;
};

/**
 * User
 */
export type User = {
    /**
     * First Name
     */
    first_name: string;
    /**
     * Locale
     */
    locale: string;
    /**
     * Unit Is Km
     */
    unit_is_km: boolean;
    /**
     * Temperature Is Celsius
     */
    temperature_is_celsius: boolean;
    /**
     * Id
     */
    id: number;
    /**
     * Google Sub
     */
    google_sub?: string | null;
    /**
     * Microsoft Sub
     */
    microsoft_sub?: string | null;
    /**
     * Profile Image Url
     */
    profile_image_url?: string | null;
    living_location?: Location | null;
    /**
     * Album Ids
     */
    album_ids?: Array<string>;
    /**
     * Is Demo
     */
    is_demo?: boolean;
    /**
     * Last Active At
     */
    last_active_at?: string;
    /**
     * Google Photos Refresh Token
     */
    google_photos_refresh_token?: string | null;
    /**
     * Google Photos Connected At
     */
    google_photos_connected_at?: string | null;
    /**
     * Has Data
     */
    readonly has_data: boolean;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * First Name
     */
    first_name?: string | null;
    /**
     * Locale
     */
    locale?: string | null;
    /**
     * Unit Is Km
     */
    unit_is_km?: boolean | null;
    /**
     * Temperature Is Celsius
     */
    temperature_is_celsius?: boolean | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * Weather
 */
export type Weather = {
    day: WeatherData;
    night?: WeatherData | null;
};

/**
 * WeatherData
 */
export type WeatherData = {
    /**
     * Temp
     */
    temp: number;
    /**
     * Feels Like
     */
    feels_like: number;
    /**
     * Icon
     */
    icon: string;
};

/**
 * PrintBundle
 *
 * Everything needed for PDF rendering in one response.
 */
export type PrintBundleWritable = {
    album: Album;
    /**
     * Steps
     */
    steps: Array<StepWritable>;
    /**
     * Segments
     */
    segments: Array<Segment>;
    /**
     * Total Distance Km
     */
    total_distance_km: number;
};

/**
 * Step
 */
export type StepWritable = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
    /**
     * Cover
     */
    cover?: string | null;
    /**
     * Pages
     */
    pages: Array<Array<string>>;
    /**
     * Unused
     */
    unused: Array<string>;
    /**
     * Uid
     */
    uid: number;
    /**
     * Aid
     */
    aid: string;
    /**
     * Id
     */
    id: number;
    /**
     * Timestamp
     */
    timestamp: number;
    /**
     * Timezone Id
     */
    timezone_id: string;
    location: Location;
    /**
     * Elevation
     */
    elevation: number;
    weather: Weather;
};

/**
 * UploadResult
 */
export type UploadResultWritable = {
    user: UserWritable;
    /**
     * Trips
     */
    trips: Array<TripMeta>;
};

/**
 * User
 */
export type UserWritable = {
    /**
     * First Name
     */
    first_name: string;
    /**
     * Locale
     */
    locale: string;
    /**
     * Unit Is Km
     */
    unit_is_km: boolean;
    /**
     * Temperature Is Celsius
     */
    temperature_is_celsius: boolean;
    /**
     * Id
     */
    id: number;
    /**
     * Google Sub
     */
    google_sub?: string | null;
    /**
     * Microsoft Sub
     */
    microsoft_sub?: string | null;
    /**
     * Profile Image Url
     */
    profile_image_url?: string | null;
    living_location?: Location | null;
    /**
     * Album Ids
     */
    album_ids?: Array<string>;
    /**
     * Is Demo
     */
    is_demo?: boolean;
    /**
     * Last Active At
     */
    last_active_at?: string;
    /**
     * Google Photos Refresh Token
     */
    google_photos_refresh_token?: string | null;
    /**
     * Google Photos Connected At
     */
    google_photos_connected_at?: string | null;
};

export type HealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health';
};

export type HealthCheckResponses = {
    /**
     * Successful Response
     */
    200: HealthStatus;
};

export type HealthCheckResponse = HealthCheckResponses[keyof HealthCheckResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type LogoutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AuthenticateData = {
    body: Credential;
    path: {
        /**
         * Provider
         */
        provider: 'google' | 'microsoft';
    };
    query?: never;
    url: '/api/v1/auth/{provider}';
};

export type AuthenticateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthenticateError = AuthenticateErrors[keyof AuthenticateErrors];

export type AuthenticateResponses = {
    /**
     * Response Authenticate
     *
     * Successful Response
     */
    200: User | null;
};

export type AuthenticateResponse = AuthenticateResponses[keyof AuthenticateResponses];

export type UploadDataData = {
    body: BodyUploadData;
    path?: never;
    query?: never;
    url: '/api/v1/users/upload';
};

export type UploadDataErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadDataError = UploadDataErrors[keyof UploadDataErrors];

export type UploadDataResponses = {
    /**
     * Successful Response
     */
    200: UploadResult;
};

export type UploadDataResponse = UploadDataResponses[keyof UploadDataResponses];

export type DeleteDemoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/demo';
};

export type DeleteDemoResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteDemoResponse = DeleteDemoResponses[keyof DeleteDemoResponses];

export type CreateDemoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/demo';
};

export type CreateDemoResponses = {
    /**
     * Successful Response
     */
    200: UploadResult;
};

export type CreateDemoResponse = CreateDemoResponses[keyof CreateDemoResponses];

export type ProcessUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/process';
};

export type ProcessUserResponses = {
    /**
     * Response 200 Process User
     *
     * Successful Response
     */
    200: Array<({
        type: 'trip_start';
    } & TripStart) | ({
        type: 'phase';
    } & PhaseUpdate) | ({
        type: 'error';
    } & ErrorData)>;
};

export type ProcessUserResponse = ProcessUserResponses[keyof ProcessUserResponses];

export type ExportDataData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/export';
};

export type ExportDataResponses = {
    /**
     * Response 200 Export Data
     *
     * Successful Response
     */
    200: Array<({
        type: 'progress';
    } & ExportProgress) | ({
        type: 'done';
    } & ExportDone) | ({
        type: 'error';
    } & ExportError)>;
};

export type ExportDataResponse = ExportDataResponses[keyof ExportDataResponses];

export type DownloadExportData = {
    body?: never;
    path: {
        /**
         * Token
         */
        token: string;
    };
    query?: never;
    url: '/api/v1/users/export/download/{token}';
};

export type DownloadExportErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DownloadExportError = DownloadExportErrors[keyof DownloadExportErrors];

export type DownloadExportResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users';
};

export type DeleteUserResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ReadUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users';
};

export type ReadUserResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type ReadUserResponse = ReadUserResponses[keyof ReadUserResponses];

export type UpdateUserData = {
    body: UserUpdate;
    path?: never;
    query?: never;
    url: '/api/v1/users';
};

export type UpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserError = UpdateUserErrors[keyof UpdateUserErrors];

export type UpdateUserResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses];

export type DownloadPdfData = {
    body?: never;
    path: {
        /**
         * Token
         */
        token: string;
    };
    query?: never;
    url: '/api/v1/albums/pdf/download/{token}';
};

export type DownloadPdfErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DownloadPdfError = DownloadPdfErrors[keyof DownloadPdfErrors];

export type DownloadPdfResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ReadAlbumData = {
    body?: never;
    path: {
        /**
         * Aid
         */
        aid: string;
    };
    query?: never;
    url: '/api/v1/albums/{aid}';
};

export type ReadAlbumErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadAlbumError = ReadAlbumErrors[keyof ReadAlbumErrors];

export type ReadAlbumResponses = {
    /**
     * Successful Response
     */
    200: AlbumMeta;
};

export type ReadAlbumResponse = ReadAlbumResponses[keyof ReadAlbumResponses];

export type UpdateAlbumData = {
    body: AlbumUpdate;
    path: {
        /**
         * Aid
         */
        aid: string;
    };
    query?: never;
    url: '/api/v1/albums/{aid}';
};

export type UpdateAlbumErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateAlbumError = UpdateAlbumErrors[keyof UpdateAlbumErrors];

export type UpdateAlbumResponses = {
    /**
     * Successful Response
     */
    200: AlbumMeta;
};

export type UpdateAlbumResponse = UpdateAlbumResponses[keyof UpdateAlbumResponses];

export type ReadMediaData = {
    body?: never;
    path: {
        /**
         * Aid
         */
        aid: string;
    };
    query?: never;
    url: '/api/v1/albums/{aid}/media';
};

export type ReadMediaErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadMediaError = ReadMediaErrors[keyof ReadMediaErrors];

export type ReadMediaResponses = {
    /**
     * Response Read Media
     *
     * Successful Response
     */
    200: Array<Media>;
};

export type ReadMediaResponse = ReadMediaResponses[keyof ReadMediaResponses];

export type ReadStepsData = {
    body?: never;
    path: {
        /**
         * Aid
         */
        aid: string;
    };
    query?: never;
    url: '/api/v1/albums/{aid}/steps';
};

export type ReadStepsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadStepsError = ReadStepsErrors[keyof ReadStepsErrors];

export type ReadStepsResponses = {
    /**
     * Response Read Steps
     *
     * Successful Response
     */
    200: Array<Step>;
};

export type ReadStepsResponse = ReadStepsResponses[keyof ReadStepsResponses];

export type ReadSegmentsData = {
    body?: never;
    path: {
        /**
         * Aid
         */
        aid: string;
    };
    query?: never;
    url: '/api/v1/albums/{aid}/segments';
};

export type ReadSegmentsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadSegmentsError = ReadSegmentsErrors[keyof ReadSegmentsErrors];

export type ReadSegmentsResponses = {
    /**
     * Response Read Segments
     *
     * Successful Response
     */
    200: Array<SegmentOutline>;
};

export type ReadSegmentsResponse = ReadSegmentsResponses[keyof ReadSegmentsResponses];

export type ReadSegmentPointsData = {
    body?: never;
    path: {
        /**
         * Aid
         */
        aid: string;
    };
    query: {
        /**
         * From Time
         */
        from_time: number;
        /**
         * To Time
         */
        to_time: number;
    };
    url: '/api/v1/albums/{aid}/segments/points';
};

export type ReadSegmentPointsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadSegmentPointsError = ReadSegmentPointsErrors[keyof ReadSegmentPointsErrors];

export type ReadSegmentPointsResponses = {
    /**
     * Response Read Segment Points
     *
     * Successful Response
     */
    200: Array<Segment>;
};

export type ReadSegmentPointsResponse = ReadSegmentPointsResponses[keyof ReadSegmentPointsResponses];

export type UpdateStepData = {
    body: StepUpdate;
    path: {
        /**
         * Aid
         */
        aid: string;
        /**
         * Sid
         */
        sid: number;
    };
    query?: never;
    url: '/api/v1/albums/{aid}/steps/{sid}';
};

export type UpdateStepErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateStepError = UpdateStepErrors[keyof UpdateStepErrors];

export type UpdateStepResponses = {
    /**
     * Successful Response
     */
    200: Step;
};

export type UpdateStepResponse = UpdateStepResponses[keyof UpdateStepResponses];

export type AdjustSegmentBoundaryData = {
    body: BoundaryAdjust;
    path: {
        /**
         * Aid
         */
        aid: string;
    };
    query?: never;
    url: '/api/v1/albums/{aid}/segments/adjust-boundary';
};

export type AdjustSegmentBoundaryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdjustSegmentBoundaryError = AdjustSegmentBoundaryErrors[keyof AdjustSegmentBoundaryErrors];

export type AdjustSegmentBoundaryResponses = {
    /**
     * Response Adjust Segment Boundary
     *
     * Successful Response
     */
    200: Array<SegmentOutline>;
};

export type AdjustSegmentBoundaryResponse = AdjustSegmentBoundaryResponses[keyof AdjustSegmentBoundaryResponses];

export type ReadPrintBundleData = {
    body?: never;
    path: {
        /**
         * Aid
         */
        aid: string;
    };
    query?: never;
    url: '/api/v1/albums/{aid}/print-bundle';
};

export type ReadPrintBundleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadPrintBundleError = ReadPrintBundleErrors[keyof ReadPrintBundleErrors];

export type ReadPrintBundleResponses = {
    /**
     * Successful Response
     */
    200: PrintBundle;
};

export type ReadPrintBundleResponse = ReadPrintBundleResponses[keyof ReadPrintBundleResponses];

export type GeneratePdfData = {
    body?: never;
    path: {
        /**
         * Aid
         */
        aid: string;
    };
    query?: {
        /**
         * Dark
         */
        dark?: boolean;
    };
    url: '/api/v1/albums/{aid}/pdf/generate';
};

export type GeneratePdfErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GeneratePdfError = GeneratePdfErrors[keyof GeneratePdfErrors];

export type GeneratePdfResponses = {
    /**
     * Response 200 Generate Pdf
     *
     * Successful Response
     */
    200: Array<({
        type: 'queued';
    } & PdfQueued) | ({
        type: 'progress';
    } & PdfProgress) | ({
        type: 'done';
    } & PdfDone) | ({
        type: 'error';
    } & PdfError)>;
};

export type GeneratePdfResponse = GeneratePdfResponses[keyof GeneratePdfResponses];

export type GetMediaData = {
    body?: never;
    path: {
        /**
         * Aid
         */
        aid: string;
        /**
         * Name
         */
        name: string;
    };
    query?: {
        /**
         * W
         */
        w?: number | null;
    };
    url: '/api/v1/albums/{aid}/media/{name}';
};

export type GetMediaErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMediaError = GetMediaErrors[keyof GetMediaErrors];

export type GetMediaResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateVideoFrameData = {
    body?: never;
    path: {
        /**
         * Aid
         */
        aid: string;
        /**
         * Name
         */
        name: string;
    };
    query: {
        /**
         * Timestamp
         */
        timestamp: number;
    };
    url: '/api/v1/albums/{aid}/media/{name}';
};

export type UpdateVideoFrameErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateVideoFrameError = UpdateVideoFrameErrors[keyof UpdateVideoFrameErrors];

export type UpdateVideoFrameResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AuthorizeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/google-photos/authorize';
};

export type AuthorizeResponses = {
    /**
     * Response Authorize
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type AuthorizeResponse = AuthorizeResponses[keyof AuthorizeResponses];

export type GooglePhotosCallbackData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/google-photos/callback';
};

export type GooglePhotosCallbackResponses = {
    /**
     * Response Google Photos Callback
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type GooglePhotosCallbackResponse = GooglePhotosCallbackResponses[keyof GooglePhotosCallbackResponses];

export type CreateSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/google-photos/sessions';
};

export type CreateSessionResponses = {
    /**
     * Successful Response
     */
    200: PickerSessionResponse;
};

export type CreateSessionResponse = CreateSessionResponses[keyof CreateSessionResponses];

export type PollSessionData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/v1/google-photos/sessions/{session_id}';
};

export type PollSessionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PollSessionError = PollSessionErrors[keyof PollSessionErrors];

export type PollSessionResponses = {
    /**
     * Successful Response
     */
    200: SessionStatusResponse;
};

export type PollSessionResponse = PollSessionResponses[keyof PollSessionResponses];

export type MatchMediaData = {
    body?: never;
    path: {
        /**
         * Aid
         */
        aid: string;
    };
    query: {
        session_id: PickerSessionId;
    };
    url: '/api/v1/google-photos/match/{aid}';
};

export type MatchMediaErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MatchMediaError = MatchMediaErrors[keyof MatchMediaErrors];

export type MatchMediaResponses = {
    /**
     * Response 200 Match Media
     *
     * Successful Response
     */
    200: Array<UpgradeMatching | UpgradeDownloading | UpgradeReplacing | UpgradeMatchSummary | UpgradeDone | UpgradeError>;
};

export type MatchMediaResponse = MatchMediaResponses[keyof MatchMediaResponses];

export type UpgradeMediaData = {
    body: UpgradeRequest;
    path: {
        /**
         * Aid
         */
        aid: string;
    };
    query?: never;
    url: '/api/v1/google-photos/upgrade/{aid}';
};

export type UpgradeMediaErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpgradeMediaError = UpgradeMediaErrors[keyof UpgradeMediaErrors];

export type UpgradeMediaResponses = {
    /**
     * Response 200 Upgrade Media
     *
     * Successful Response
     */
    200: Array<UpgradeMatching | UpgradeDownloading | UpgradeReplacing | UpgradeMatchSummary | UpgradeDone | UpgradeError>;
};

export type UpgradeMediaResponse = UpgradeMediaResponses[keyof UpgradeMediaResponses];

export type DisconnectData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/google-photos/connection';
};

export type DisconnectResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
