"""Regression tests for the processing pipeline."""

from pathlib import Path
from unittest.mock import patch

from sqlalchemy.ext.asyncio import create_async_engine
from sqlalchemy.pool import StaticPool
from sqlmodel import SQLModel, select
from sqlmodel.ext.asyncio.session import AsyncSession

from app.logic.pipeline import _save_reupload
from app.models.album import Album
from app.models.polarsteps import Point
from app.models.segment import Segment, SegmentKind
from app.models.step import Step
from app.models.user import User
from app.models.weather import Weather, WeatherData


def _make_points(times: list[float]) -> list[Point]:
    return [
        Point(lat=52.0 + i * 0.01, lon=4.0 + i * 0.01, time=t)
        for i, t in enumerate(times)
    ]


AID = "test-trip"
UID = 1


class TestSaveReuploadDeletesSegments:
    """Regression for stale Segments on reupload.

    _save_reupload deleted Steps for reconciled albums but left stale Segments
    in the DB.  Segments FK-cascade from Album, not Step, so deleting Steps
    alone had no effect on Segments.
    """

    async def test_reconciled_album_segments_are_deleted(self, tmp_path: Path) -> None:
        engine = create_async_engine(
            "sqlite+aiosqlite://",
            connect_args={"check_same_thread": False},
            poolclass=StaticPool,
        )
        async with engine.begin() as conn:
            await conn.run_sync(SQLModel.metadata.create_all)

        # Seed: user, album, step, and segment.
        async with AsyncSession(engine) as session:
            user = User(
                id=UID,
                first_name="Test",
                locale="en-US",
                unit_is_km=True,
                temperature_is_celsius=True,
                google_sub="test-sub",
            )
            session.add(user)
            album = Album(
                uid=UID,
                id=AID,
                title="Old Trip",
                subtitle="",
                excluded_steps=[],
                maps_ranges=[],
                front_cover_photo="a.jpg",
                back_cover_photo="b.jpg",
                colors={},
                media=[],
                font="Assistant",
                body_font="Frank Ruhl Libre",
            )
            session.add(album)
            step = Step(
                uid=UID,
                aid=AID,
                id=1,
                name="Old Step",
                description="",
                cover=None,
                pages=[],
                unused=[],
                timestamp=1_000_000.0,
                timezone_id="UTC",
                location=None,
                elevation=0,
                weather=Weather(
                    day=WeatherData(temp=20.0, feels_like=18.0, icon="sun"),
                    night=None,
                ),
            )
            session.add(step)
            segment = Segment(
                uid=UID,
                aid=AID,
                start_time=100.0,
                end_time=500.0,
                kind=SegmentKind.driving,
                timezone_id="UTC",
                points=_make_points([100.0, 300.0, 500.0]),
            )
            session.add(segment)
            await session.commit()

        # New objects for the reupload (new step, no new segments — they'd
        # normally be regenerated by the segment pipeline, but the reconcile
        # path doesn't produce them).
        new_album = Album(
            uid=UID,
            id=AID,
            title="Reconciled Trip",
            subtitle="",
            excluded_steps=[],
            maps_ranges=[],
            front_cover_photo="c.jpg",
            back_cover_photo="d.jpg",
            colors={},
            media=[],
            body_font="Frank Ruhl Libre",
        )
        new_step = Step(
            uid=UID,
            aid=AID,
            id=2,
            name="New Step",
            description="",
            cover=None,
            pages=[],
            unused=[],
            timestamp=2_000_000.0,
            timezone_id="UTC",
            location=None,
            elevation=0,
            weather=Weather(
                day=WeatherData(temp=25.0, feels_like=23.0, icon="cloud"),
                night=None,
            ),
        )

        trip_dir = tmp_path / AID
        trip_dir.mkdir()

        with patch("app.logic.pipeline.get_engine", return_value=engine):
            await _save_reupload(
                uid=UID,
                objects=[new_album, new_step],
                reconciled_aids={AID},
                existing_albums={AID: album},
                trip_dirs=[trip_dir],
            )

        # Verify: old segment must be gone, old step must be gone.
        async with AsyncSession(engine) as session:
            segments = (await session.exec(select(Segment))).all()
            steps = (await session.exec(select(Step))).all()
            albums = (await session.exec(select(Album))).all()

        assert len(segments) == 0, f"Stale segments remain: {segments}"
        assert len(steps) == 1
        assert steps[0].name == "New Step"
        assert len(albums) == 1
        assert albums[0].title == "Reconciled Trip"
