"""Media upgrade package - matching and replacing compressed media with originals."""

# Re-export public API so existing `from app.logic.media_upgrade import X` works.
from .matching import (
    _CROSS_TYPE_COST,
    _FALLBACK_MAX_DIMENSION,
    MATCH_THRESHOLD,
    HashedMedia,
    LocalHash,
    MatchResult,
    StepWindow,
    _pairwise_distance,
    _parse_timestamp,
    bucket_by_window,
    build_cost_matrix,
    build_step_windows,
    compute_phash,
    compute_phash_from_bytes,
    compute_phash_from_path,
    cross_step_fallback,
    deduplicate_items,
    extract_video_frame_hashes,
    match_across_windows,
    match_within_window,
)
from .pipeline import (
    UpgradeDone,
    UpgradeDownloading,
    UpgradeError,
    UpgradeEvent,
    UpgradeMatching,
    UpgradeMatchSummary,
    _clear_caches,
    apply_upgrade_results,
    cleanup_orphaned_tmp,
    execute_upgrade,
    run_matching,
)
from .processing import (
    _MAX_LONG_EDGE,
    process_photo_sync,
    process_video,
    replace_photo,
    replace_video,
)

__all__ = [
    "MATCH_THRESHOLD",
    "_CROSS_TYPE_COST",
    "_FALLBACK_MAX_DIMENSION",
    "_MAX_LONG_EDGE",
    "HashedMedia",
    "LocalHash",
    "MatchResult",
    "StepWindow",
    "UpgradeDone",
    "UpgradeDownloading",
    "UpgradeError",
    "UpgradeEvent",
    "UpgradeMatchSummary",
    "UpgradeMatching",
    "_clear_caches",
    "_pairwise_distance",
    "_parse_timestamp",
    "apply_upgrade_results",
    "bucket_by_window",
    "build_cost_matrix",
    "build_step_windows",
    "cleanup_orphaned_tmp",
    "compute_phash",
    "compute_phash_from_bytes",
    "compute_phash_from_path",
    "cross_step_fallback",
    "deduplicate_items",
    "execute_upgrade",
    "extract_video_frame_hashes",
    "match_across_windows",
    "match_within_window",
    "process_photo_sync",
    "process_video",
    "replace_photo",
    "replace_video",
    "run_matching",
]
