import abc
from abc import ABC
from typing import Any, Self

class AdapterHTTPError(IOError):
    def __init__(self, message, *, status_code, headers, text) -> None: ...

class BaseAdapter(abc.ABC):
    def __init__(self, *, proxies, ssl_context) -> None: ...
    @abc.abstractmethod
    def get_json(self, url, *, timeout, headers) -> None: ...
    @abc.abstractmethod
    def get_text(self, url, *, timeout, headers) -> None: ...

class BaseAsyncAdapter(BaseAdapter, ABC):
    async def __aenter__(self) -> Self: ...
    async def __aexit__(self, exc_type, exc_val, exc_tb) -> None: ...

class AioHTTPAdapter(BaseAsyncAdapter):
    def __init__(self, *, proxies, ssl_context) -> None: ...
    @property
    def session(self) -> ClientSession | Any: ...
    async def __aenter__(self) -> Self: ...
    async def __aexit__(self, exc_type, exc_val, exc_tb) -> None: ...
    async def get_text(self, url, *, timeout, headers) -> str | Any: ...
    async def get_json(self, url, *, timeout, headers) -> Any: ...
