"""add safe_margin_mm to album

Revision ID: 27083dd2e4fd
Revises: 6eee573c95c0
Create Date: 2026-04-03 21:44:15.828247

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '27083dd2e4fd'
down_revision = '6eee573c95c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('safe_margin_mm', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('album', 'safe_margin_mm')
    # ### end Alembic commands ###
