"""add profile_image_path to user

Revision ID: 4c070c5eac8d
Revises: d7be05cf7e4d
Create Date: 2026-03-10 20:51:01.791952

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4c070c5eac8d'
down_revision = 'd7be05cf7e4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_image_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_image_path')
    # ### end Alembic commands ###
