"""add timezone_id to segment

Revision ID: 505c5fb1dc82
Revises: c3d4e5f60002
Create Date: 2026-03-29 06:07:12.509906

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '505c5fb1dc82'
down_revision = 'c3d4e5f60002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('segment', sa.Column('timezone_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('segment', 'timezone_id')
    # ### end Alembic commands ###
