"""initial revision

Revision ID: 8ec97bc11b0c
Revises:
Create Date: 2026-03-12 22:45:06.069779

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8ec97bc11b0c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('profile_image_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('living_location', sa.JSON(), nullable=False),
    sa.Column('locale', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('unit_is_km', sa.Boolean(), nullable=False),
    sa.Column('temperature_is_celsius', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('album_ids', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('album',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('subtitle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('steps_ranges', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('maps_ranges', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('front_cover_photo', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('back_cover_photo', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('colors', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['uid'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid', 'id')
    )
    op.create_table('segment',
    sa.Column('kind', sa.Enum('flight', 'hike', 'walking', 'driving', name='segmentkind'), nullable=False),
    sa.Column('points', sa.JSON(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('aid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['uid', 'aid'], ['album.uid', 'album.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uid'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid', 'aid', 'start_time', 'end_time')
    )
    op.create_table('step',
    sa.Column('cover', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pages', sa.JSON(), nullable=False),
    sa.Column('unused', sa.JSON(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('aid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('timezone_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('location', sa.JSON(), nullable=False),
    sa.Column('elevation', sa.Integer(), nullable=False),
    sa.Column('weather', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['uid', 'aid'], ['album.uid', 'album.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uid'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid', 'aid', 'idx')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('step')
    op.drop_table('segment')
    op.drop_table('album')
    op.drop_table('user')
    # ### end Alembic commands ###
