"""add body_font to album

Revision ID: afedc79fdb8b
Revises: b2c0d72bbd42
Create Date: 2026-03-30 10:03:36.236915

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'afedc79fdb8b'
down_revision = 'b2c0d72bbd42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('body_font', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False, server_default='Frank Ruhl Libre'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('album', 'body_font')
    # ### end Alembic commands ###
