"""add google photos columns

Revision ID: b119e3ee2c5b
Revises: 086472e34c04
Create Date: 2026-04-15 20:10:20.895313

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b119e3ee2c5b'
down_revision = '086472e34c04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('upgraded_photos', sa.JSON(), server_default='{}', nullable=False))
    op.add_column('user', sa.Column('google_photos_refresh_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('google_photos_connected_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'google_photos_connected_at')
    op.drop_column('user', 'google_photos_refresh_token')
    op.drop_column('album', 'upgraded_photos')
    # ### end Alembic commands ###
