"""replace_steps_ranges_with_excluded_steps

Revision ID: b2c0d72bbd42
Revises: 505c5fb1dc82
Create Date: 2026-03-30 02:58:44.714468

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b2c0d72bbd42'
down_revision = '505c5fb1dc82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('excluded_steps', sa.JSON(), nullable=False, server_default='[]'))
    op.drop_column('album', 'steps_ranges')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('steps_ranges', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('album', 'excluded_steps')
    # ### end Alembic commands ###
