"""Add album page numbers

Revision ID: b45c61407294
Revises: fffe0591309b
Create Date: 2026-09-10 00:49:12.693598

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b45c61407294'
down_revision = 'fffe0591309b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('show_page_numbers', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.alter_column('album', 'show_page_numbers', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('album', 'show_page_numbers')
    # ### end Alembic commands ###
