"""add first_name and last_name to user

Revision ID: d7be05cf7e4d
Revises: 4d5e0f13354e
Create Date: 2026-03-10 20:39:48.626846

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd7be05cf7e4d'
down_revision = '4d5e0f13354e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False, server_default=''))
    op.add_column('user', sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
