"""add media_resolution_warning_preset to album.

Revision ID: dcb0d4e8f8b3
Revises: b119e3ee2c5b
Create Date: 2026-05-06 22:02:00.000000

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "dcb0d4e8f8b3"
down_revision = "b119e3ee2c5b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "album",
        sa.Column(
            "media_resolution_warning_preset",
            sa.String(length=20),
            server_default="relaxed",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("album", "media_resolution_warning_preset")
    # ### end Alembic commands ###
