"""initial schema

Revision ID: f097a964b67c
Revises:
Create Date: 2026-03-30 21:01:25.114700

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f097a964b67c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('flight', 'hike', 'walking', 'driving', name='segmentkind').create(op.get_bind())
    op.create_table('user',
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('locale', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unit_is_km', sa.Boolean(), nullable=False),
    sa.Column('temperature_is_celsius', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_sub', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('microsoft_sub', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('profile_image_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('living_location', sa.JSON(), nullable=True),
    sa.Column('album_ids', sa.JSON(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('google_sub IS NOT NULL OR microsoft_sub IS NOT NULL', name='ck_user_has_provider'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_google_sub'), 'user', ['google_sub'], unique=True)
    op.create_index(op.f('ix_user_microsoft_sub'), 'user', ['microsoft_sub'], unique=True)
    op.create_table('album',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('subtitle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('excluded_steps', sa.JSON(), nullable=False),
    sa.Column('maps_ranges', sa.JSON(), nullable=False),
    sa.Column('front_cover_photo', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('back_cover_photo', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('font', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('body_font', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('colors', sa.JSON(), nullable=False),
    sa.Column('media', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['uid'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid', 'id')
    )
    op.create_table('segment',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('aid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('kind', postgresql.ENUM('flight', 'hike', 'walking', 'driving', name='segmentkind', create_type=False), nullable=False),
    sa.Column('timezone_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('points', sa.JSON(), nullable=False),
    sa.Column('route', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['uid', 'aid'], ['album.uid', 'album.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uid'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid', 'aid', 'start_time', 'end_time')
    )
    op.create_table('step',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cover', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pages', sa.JSON(), nullable=False),
    sa.Column('unused', sa.JSON(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('aid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('timezone_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('location', sa.JSON(), nullable=False),
    sa.Column('elevation', sa.Integer(), nullable=False),
    sa.Column('weather', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['uid', 'aid'], ['album.uid', 'album.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uid'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid', 'aid', 'id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('step')
    op.drop_table('segment')
    op.drop_table('album')
    op.drop_index(op.f('ix_user_microsoft_sub'), table_name='user')
    op.drop_index(op.f('ix_user_google_sub'), table_name='user')
    op.drop_table('user')
    sa.Enum('flight', 'hike', 'walking', 'driving', name='segmentkind').drop(op.get_bind())
    # ### end Alembic commands ###
