"""add font to album

Revision ID: f13331818c11
Revises: afedc79fdb8b
Create Date: 2026-03-30 10:49:48.802225

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f13331818c11'
down_revision = 'afedc79fdb8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('font', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False, server_default='Assistant'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('album', 'font')
    # ### end Alembic commands ###
