# /// script
# dependencies = [
#   "httpx",
# ]
# ///

"""Download Google Fonts woff2 subsets and generate @font-face CSS from fonts.json."""

import json
import re
import shutil
import sys
from pathlib import Path

import httpx

ROOT = Path(__file__).resolve().parent.parent
FONTS_JSON = ROOT / "fonts.json"
FONTS_DIR = ROOT / "frontend" / "public" / "fonts"
CSS_OUT = ROOT / "frontend" / "src" / "styles" / "fonts.css"

# Chrome user-agent so Google Fonts serves woff2 (not woff or ttf)
USER_AGENT = (
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"
)

# Subsets in the order they appear in CSS comments — we require all three
REQUIRED_SUBSETS = ("hebrew", "latin-ext", "latin")

# JetBrains Mono is self-hosted but not user-selectable — always include it
EXTRA_FONTS = [
    {
        "family": "JetBrains Mono",
        "category": "monospace",
        "weights": "100..800",
        "subsets": ("latin",),
    }
]


def slugify(family: str) -> str:
    """'Frank Ruhl Libre' -> 'frank-ruhl-libre'"""
    return family.lower().replace(" ", "-")


def weight_spec(weights: str) -> str:
    """'300..900' -> 'wght@300..900', '400' -> 'wght@400'"""
    return f"wght@{weights}"


def fetch_css(client: httpx.Client, family: str, weights: str) -> str:
    """Fetch the CSS2 stylesheet for a font family."""
    url = (
        f"https://fonts.googleapis.com/css2"
        f"?family={family.replace(' ', '+')}:{weight_spec(weights)}"
    )
    resp = client.get(url, headers={"User-Agent": USER_AGENT})
    resp.raise_for_status()
    return resp.text


def parse_font_faces(css: str) -> list[dict]:
    """Parse @font-face blocks from Google Fonts CSS.

    Google Fonts CSS has comments like `/* latin */` before each block.
    We extract the subset name from these comments.
    """
    blocks = []
    # Split on @font-face, keeping the comment before each block
    parts = re.split(r"/\*\s*([a-z-]+)\s*\*/\s*@font-face\s*\{", css)
    # parts[0] is preamble (empty or license), then alternating: subset, block-body
    for i in range(1, len(parts), 2):
        subset = parts[i].strip()
        body = parts[i + 1].split("}")[0]

        # Extract fields from the CSS block
        font_family = re.search(r"font-family:\s*'([^']+)'", body)
        font_weight = re.search(r"font-weight:\s*([^;]+)", body)
        unicode_range = re.search(r"unicode-range:\s*([^;]+)", body)
        src_url = re.search(r"url\(([^)]+\.woff2)\)", body)

        if not (font_family and src_url):
            continue

        blocks.append(
            {
                "subset": subset,
                "family": font_family.group(1),
                "weight": font_weight.group(1).strip() if font_weight else "400",
                "unicode_range": unicode_range.group(1).strip()
                if unicode_range
                else None,
                "url": src_url.group(1),
            }
        )

    return blocks


def download_font(client: httpx.Client, url: str, dest: Path, *, clean: bool) -> None:
    """Download a woff2 file if it doesn't already exist (or --clean was passed)."""
    if not clean and dest.exists() and dest.stat().st_size > 0:
        return
    resp = client.get(url)
    resp.raise_for_status()
    dest.write_bytes(resp.content)


def generate_css(all_faces: list[dict]) -> str:
    """Generate the fonts.css content from parsed font face data."""
    lines = [
        "/*",
        " * AUTO-GENERATED by scripts/generate_fonts.py — do not edit.",
        " * Source of truth: fonts.json",
        " *",
        " * font-display: block — browser waits for font load before rendering.",
        " * Critical for PDF generation: prevents Playwright capturing before swap.",
        " */",
        "",
    ]

    current_family = None
    for face in all_faces:
        if face["family"] != current_family:
            if current_family is not None:
                lines.append("")
            lines.append(f"/* --- {face['family']} --- */")
            current_family = face["family"]

        lines.append("")
        lines.append(f"/* {face['subset']} */")
        lines.append("@font-face {")
        lines.append(f'  font-family: "{face["family"]}";')
        lines.append("  font-style: normal;")
        lines.append(f"  font-weight: {face['weight']};")
        lines.append("  font-display: block;")
        lines.append(f'  src: url("/fonts/{face["filename"]}") format("woff2");')
        if face.get("unicode_range"):
            lines.append(f"  unicode-range: {face['unicode_range']};")
        lines.append("}")

    lines.append("")  # trailing newline
    return "\n".join(lines)


def main() -> None:
    clean = "--clean" in sys.argv

    registry = json.loads(FONTS_JSON.read_text())
    fonts = registry["fonts"]

    if clean and FONTS_DIR.exists():
        shutil.rmtree(FONTS_DIR)
    FONTS_DIR.mkdir(parents=True, exist_ok=True)
    CSS_OUT.parent.mkdir(parents=True, exist_ok=True)

    all_faces: list[dict] = []

    with httpx.Client(timeout=30, follow_redirects=True) as client:
        # Process registry fonts (all require hebrew + latin-ext + latin)
        for font in fonts:
            family = font["family"]
            slug = slugify(family)
            weights = font["weights"]

            print(f"  {family}...", end=" ", flush=True)
            css = fetch_css(client, family, weights)
            blocks = parse_font_faces(css)

            # Filter to required subsets only
            subset_blocks = [b for b in blocks if b["subset"] in REQUIRED_SUBSETS]
            found_subsets = {b["subset"] for b in subset_blocks}
            missing = set(REQUIRED_SUBSETS) - found_subsets
            if missing:
                print(f"WARNING: missing subsets {missing}")
            else:
                print(f"ok ({len(subset_blocks)} subsets)")

            # Static fonts (semicolon-separated weights) need per-weight filenames
            is_static = ";" in weights

            for block in subset_blocks:
                weight_suffix = f"-{block['weight']}" if is_static else ""
                filename = f"{slug}-{block['subset']}{weight_suffix}.woff2"
                dest = FONTS_DIR / filename
                download_font(client, block["url"], dest, clean=clean)
                all_faces.append({**block, "filename": filename})

        # Process extra fonts (JetBrains Mono — latin only)
        for font in EXTRA_FONTS:
            family = font["family"]
            slug = slugify(family)
            weights = font["weights"]
            required = font.get("subsets", REQUIRED_SUBSETS)
            is_static = ";" in weights

            print(f"  {family}...", end=" ", flush=True)
            css = fetch_css(client, family, weights)
            blocks = parse_font_faces(css)

            subset_blocks = [b for b in blocks if b["subset"] in required]
            print(f"ok ({len(subset_blocks)} subsets)")

            for block in subset_blocks:
                weight_suffix = f"-{block['weight']}" if is_static else ""
                filename = f"{slug}-{block['subset']}{weight_suffix}.woff2"
                dest = FONTS_DIR / filename
                download_font(client, block["url"], dest, clean=clean)
                all_faces.append({**block, "filename": filename})

    # Generate CSS
    css_content = generate_css(all_faces)
    CSS_OUT.write_text(css_content)
    print(f"\n  Generated {CSS_OUT.relative_to(ROOT)}")
    print(
        f"  {len(all_faces)} font faces, {sum(1 for f in FONTS_DIR.iterdir() if f.suffix == '.woff2')} woff2 files"
    )


if __name__ == "__main__":
    print("Generating fonts from fonts.json...")
    main()
    print("Done.")
