# /// script
# dependencies = [
#   "httpx",
# ]
# ///

"""Download Google Fonts woff2 subsets and generate @font-face CSS from fonts.json."""

import json
import re
import shutil
import sys
from pathlib import Path

import httpx

from lib.downloads import download_atomic

ROOT = Path(__file__).resolve().parent.parent
FONTS_JSON = ROOT / "frontend" / "fonts.json"
FONTS_DIR = ROOT / "frontend" / "public" / "fonts"
CSS_OUT = ROOT / "frontend" / "src" / "styles" / "fonts.css"

# Chrome user-agent so Google Fonts serves woff2 (not woff or ttf)
USER_AGENT = (
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"
)

# Subsets we require for all user-selectable fonts
REQUIRED_SUBSETS = frozenset(("hebrew", "latin-ext", "latin"))

# JetBrains Mono is self-hosted but not user-selectable - always include it
EXTRA_FONTS = [
    {"family": "JetBrains Mono", "weights": "100..800", "subsets": ("latin",)},
]

# Extract (subset, weight, url, unicode_range) from Google Fonts CSS.
# Google's CSS always emits properties in this order:
#   font-family → font-style → font-weight → src → unicode-range
FACE_RE = re.compile(
    r"/\*\s*([a-z-]+)\s*\*/\s*@font-face\s*\{[^}]*"
    r"font-weight:\s*([^;]+);[^}]*"
    r"url\((https?://[^)]+\.woff2)\)[^}]*"
    r"unicode-range:\s*([^;]+);",
    re.DOTALL,
)

CSS_HEADER = """\
/*
 * AUTO-GENERATED by scripts/generate_fonts.py - do not edit.
 * Source of truth: frontend/fonts.json
 *
 * font-display: block - browser waits for font load before rendering.
 * Critical for PDF generation: prevents Playwright capturing before swap.
 */
"""


def slugify(family: str) -> str:
    """'Frank Ruhl Libre' -> 'frank-ruhl-libre'"""
    return family.lower().replace(" ", "-")


def fetch_faces(
    client: httpx.Client,
    family: str,
    weights: str,
    subsets: frozenset[str],
    *,
    warn_missing: bool,
) -> list[dict]:
    """Fetch Google Fonts CSS and extract matching font-face entries."""
    url = (
        f"https://fonts.googleapis.com/css2"
        f"?family={family.replace(' ', '+')}:wght@{weights}"
    )
    css = client.get(url, headers={"User-Agent": USER_AGENT}).raise_for_status().text

    slug = slugify(family)
    faces = []
    for subset, weight, src_url, unicode_range in FACE_RE.findall(css):
        if subset not in subsets:
            continue
        is_static = ".." not in weights
        weight_suffix = f"-{weight.strip()}" if is_static else ""
        filename = f"{slug}-{subset}{weight_suffix}.woff2"
        faces.append(
            {
                "family": family,
                "subset": subset,
                "weight": weight.strip(),
                "url": src_url,
                "unicode_range": unicode_range.strip(),
                "filename": filename,
            }
        )

    missing = subsets - {f["subset"] for f in faces}
    if missing and warn_missing:
        print(f"WARNING: missing subsets {missing}")
    print(f"ok ({len(faces)} subsets)")

    return faces


def download_font(_client: httpx.Client, url: str, dest: Path, *, clean: bool) -> None:
    """Download a woff2 file if it doesn't already exist (or --clean was passed)."""
    download_atomic(url, dest, skip_existing=not clean)


def generate_css(all_faces: list[dict]) -> str:
    """Generate the fonts.css content from font face data."""
    blocks = [CSS_HEADER]
    current_family = None
    for face in all_faces:
        if face["family"] != current_family:
            if current_family is not None:
                blocks.append("")
            blocks.append(f"/* --- {face['family']} --- */")
            current_family = face["family"]

        blocks.append(f"""\
/* {face["subset"]} */
@font-face {{
  font-family: "{face["family"]}";
  font-style: normal;
  font-weight: {face["weight"]};
  font-display: block;
  src: url("/fonts/{face["filename"]}") format("woff2");
  unicode-range: {face["unicode_range"]};
}}""")

    return "\n\n".join(blocks) + "\n"


def main() -> None:
    clean = "--clean" in sys.argv

    registry = json.loads(FONTS_JSON.read_text())
    fonts = registry["fonts"]

    if clean and FONTS_DIR.exists():
        shutil.rmtree(FONTS_DIR)
    FONTS_DIR.mkdir(parents=True, exist_ok=True)
    CSS_OUT.parent.mkdir(parents=True, exist_ok=True)

    all_fonts = [
        {
            "family": f["family"],
            "weights": f["weights"],
            "subsets": REQUIRED_SUBSETS,
            "warn_missing": True,
        }
        for f in fonts
    ] + [
        {
            "family": f["family"],
            "weights": f["weights"],
            "subsets": frozenset(f.get("subsets", REQUIRED_SUBSETS)),
            "warn_missing": False,
        }
        for f in EXTRA_FONTS
    ]

    all_faces: list[dict] = []

    with httpx.Client(timeout=30, follow_redirects=True) as client:
        for spec in all_fonts:
            print(f"  {spec['family']}...", end=" ", flush=True)
            faces = fetch_faces(
                client,
                spec["family"],
                spec["weights"],
                spec["subsets"],
                warn_missing=spec["warn_missing"],
            )
            for face in faces:
                download_font(
                    client, face["url"], FONTS_DIR / face["filename"], clean=clean
                )
            all_faces.extend(faces)

    CSS_OUT.write_text(generate_css(all_faces))
    print(f"\n  Generated {CSS_OUT.relative_to(ROOT)}")
    woff2_count = sum(1 for f in FONTS_DIR.iterdir() if f.suffix == ".woff2")
    print(f"  {len(all_faces)} font faces, {woff2_count} woff2 files")


if __name__ == "__main__":
    print("Generating fonts from fonts.json...")
    main()
    print("Done.")
