services:
  backend:
    command: >-
      sh -c "alembic upgrade head &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000
      --proxy-headers --log-config app/core/uvicorn_logging.json"

  frontend:
    ports:
      - "127.0.0.1:5173:8080"
    depends_on:
      backend:
        condition: service_healthy
      object-storage-init:
        condition: service_completed_successfully

networks:
  backend:
    internal: false
  frontend:
    name: ${COMPOSE_PROJECT_NAME}_frontend
    external: false
