# ruff: noqa: ANN401
# pyright: reportExplicitAny=false, reportAny=false
from types import FunctionType
from typing import Any

def full_name(func: FunctionType) -> str: ...

# noinspection PyDefaultArgument
def args_to_key(
    base: tuple[Any, ...],
    args: tuple[Any, ...],
    kwargs: dict[str, Any],
    typed: bool,
    ignore: set[int | str],  # noqa: PYI011
) -> tuple[Any, ...]: ...

class Cache:
    def __init__(self, directory: str, timeout: int = ...) -> None: ...
    def __setitem__(self, key: tuple[Any, ...], value: Any) -> None: ...
    def __getitem__(self, key: tuple[Any, ...]) -> Any: ...
    def __contains__(self, key: tuple[Any, ...]) -> bool: ...
    def stats(self, enable: bool = True, reset: bool = False) -> tuple[int, int]: ...
    def volume(self) -> int: ...
