name: Lint

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - uses: astral-sh/setup-uv@v7
      - run: uv sync --all-packages
      - run: bun install --frozen-lockfile
      - name: Ruff check
        run: uv run ruff check app
        working-directory: backend
      - name: Ruff format
        run: uv run ruff format app --check
        working-directory: backend
      - name: ty check
        run: uv run ty check
        working-directory: backend
      - name: ESLint
        run: bun run lint
        working-directory: frontend
